POST http://localhost:3003/api/blogs/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNoYWZTYXIiLCJpZCI6IjZhOGU4OTkzMmNjMDRkMmMzMjFlZWFiYiIsImlhdCI6MTc4NzgyMDM5MiwiZXhwIjoxNzg3ODIzOTkyfQ.U6AGlahOhOh5qTym4IsozFc_nNKFraAiomh08ppL4L0

{
	"title": "This is The First Post",
	"author": "Shafaq Sarfraz",
	"url": "http://firstpost.com",
	"likes": 10,
	"userId": "6a8a700c1ebe9fc14b3ebe4e"
}

###
POST http://localhost:3003/api/blogs/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhhbXphU2FyIiwiaWQiOiI2YThmZjkzNTY2NWNlODFmMjE3YTY1ZjIiLCJpYXQiOjE3ODc4MjA0MTgsImV4cCI6MTc4NzgyNDAxOH0.BwE5TmzWJ56YOjc1Z0mro773PM_FipMrkYnRKpJrQ2E

{
	"title": "This is A Pretentious Post",
	"author": "Hamza Sarfraz",
	"url": "http://pretentiouspost.com",
	"likes": 10,
	"userId": "6a8e8d9d067aa71a420fd69f"
}

###
POST http://localhost:3003/api/blogs/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNoYWZTYXIiLCJpZCI6IjZhOGU4OTkzMmNjMDRkMmMzMjFlZWFiYiIsImlhdCI6MTc4NzgyNjkxMSwiZXhwIjoxNzg3ODMwNTExfQ.WYyPJqnweDkcBlpGpgBXu8hH06eHC4zn2Jh52Tung84

{
	"title": "Testing Middleware Integration",
	"author": "Shafaq Sarfraz",
	"url": "http://firstpost.com",
	"likes": 10,
	"userId": "6a8a700c1ebe9fc14b3ebe4e"
}