POST http://localhost:3003/api/users/
content-type: application/json

{
	"name": "Shafaq Sarfraz",
	"username": "ShafSar",
	"password": "mmm"
}

###
POST http://localhost:3003/api/users/
content-type: application/json

{
	"name": "Hamza Sarfraz",
	"username": "HamzaSar",
	"password": "hamzasar"
}


###
GET http://localhost:3003/api/users/